load carsmall;
y = MPG; 
x1 = Weight; x2 = Horsepower; 
X = [ones(length(x1),1) x1 x2]; 
b = regress(y,X);
x1fit = min(x1):100:max(x1);
x2fit = min(x2):10:max(x2);
[X1FIT,X2FIT]=meshgrid(x1fit,x2fit);
YFIT=b(1)+b(2)*X1FIT+b(3)*X2FIT; 
scatter3(x1,x2,y,'filled'); hold on;
mesh(X1FIT,X2FIT,YFIT); hold off;
xlabel('Weight'); 
ylabel('Horsepower'); 
zlabel('MPG'); view(50,10);
[b,bint,r,rint,stats]=regress(y,X);